baseURL = 'https://Shreyas3105.github.io/portfolio/'
languageCode = 'en-us'
title = 'Shreyas Agarwal'
theme = 'gohugo-theme-ananke'
 
[menu]
[[menu.main]]
    name = "HOME"
    url = "/"
    weight = 1
 
  [[menu.main]]
    name = "PROJECTS"
    url = "/projects/"
    weight = 2
 
  [[menu.main]]
    name = "RESEARCH"
    url = "/publications/"
    weight = 3
 
  [[menu.main]]
    name = "ABOUT ME"
    url = "/about/"
    weight = 5