baseURL = 'https://Shreyas3105.github.io/Website/'
languageCode = 'en-us'
title = 'Personal Website - Shreyas Agarwal'
theme = 'beautifulhugo'
 
[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
 
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
 
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
 
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5